### ISSUE TITLE
Need to run Install again after kernel upgrade.

### ISSUE THREAD

**Issue by Skammi** [mangdangroboticsclub/mini_pupper_bsp#13]
I did an sudo apt update, sudo apt upgrade. Which upgraded the kernel from vmlinuz-5.4.0-1070-raspi to vmlinuz-5.4.0-1071-raspiI.
After that the battery monitor didn't work. Trouble shooting showed that the kernel upgrade also replaced: i2c3.dtbo and i2c4.dtbo in /boot/firmware/overlays/.
The remedy was to run ./install again. Probably running ./install in FuelGauge and EEPROM should be enough in the future.

**Comment by hdumcke** [comment]
it should be sufficient to just run update_kernel_modules.sh.
There is a PR waiting to be merged that will use DKMS to automatically update kernel modules when apt upgrade updates the kernel. Right now we have a code freeze until the ROSCon workshop is over. 

I suggest we close this issue once the PR is merged

**Comment by mangdangroboticsclub** [comment]
close this issue as the PR is merged
