### ISSUE TITLE
Sound has issues when desktop installed on ubuntu server 20.04.5

### ISSUE THREAD

**Issue by Skammi** [mangdangroboticsclub/mini_pupper_bsp#14]
Sound fails when having the desktop installed on ubuntu server 20.04.5 following the description below.
When not logged-in on the desktop using ssh the command:
`
mpg123 -qa hw:01,00 ~/QuadrupedRobot/mini_pupper_bsp/Audio/power_on.mp3
`
fails with:
`
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
Can't open libao driver with device hw:01,00 (is device in use?)
`
When logged-in to the desktop in a terminal and via ssh the command:
`
 mpg123 -va hw:01,00 ~/QuadrupedRobot/mini_pupper_bsp/Audio/power_on.mp3
`
responds with:
...
`Directory: /home/jac/QuadrupedRobot/mini_pupper_bsp/Audio`
`Playing MPEG stream from power_on.mp3`
`MPEG 1.0, Layer: III, Freq: 44100, mode: Stereo, modext: 0, BPF : 2560`
`Channels: 2, copyright: No, original: No, CRC: No, emphasis: 0.`
`Bitrate: 128 Kbits/s, Extension value: 0`
`Audio: 1:1 conversion, rate: 44100, encoding: signed 16 bit, channels: 2`                                                                
`[0:00] Decoding of power_on.mp3 finished.`

Still no sound is played from the speaker!

However using the sound settings app on the desktop with as output Device any but the headphones produces a sound.

I worked before with the server install without adding the desktop and that did not produce the above issues. I went for the desktop to have an easier way to calibrate. .... Bad mistake will go back to the server without desktop again

**Comment by mangdangroboticsclub** [comment]
we only maintain ubuntu 22.04 now, thanks
