### ISSUE TITLE
Incorrect version string for Python module

### ISSUE THREAD

**Issue by hdumcke** [mangdangroboticsclub/mini_pupper_bsp#23]
ubuntu@minipupper:~$ pip freeze | grep MangDang
MangDang===0.1-dirty

Expected result would be
MangDang===0.1

This is due to the fact that we install FuelGauge before we install the Python module and that install process generates a binary file

There is also an issue with System. We query the environment to detect the correct sound driver and then modify 
	modified:   System/rc.local
	modified:   test.sh
	
I suggest we move the installation of the Python module before the installation of other component so that we have a clean git repo  to generate a clean version string.  There are other options like changing the .gitignore file but this will not work for test.sh. We could also just generate the environment variable PBR_VERSION early and leave the installation of the python module where it currently is. 

I still think my suggestion is the best option

**Comment by Tiryoh** [comment]
I agree with switching the order.
There is a warning about PEP440, but I think that is a separate topic and we can go on with this.
If we need to discuss it, let's create a another issue.
