### ISSUE TITLE
use PCA9685 chipset to control servo

### ISSUE THREAD

**Issue by mangdangroboticsclub** [mangdangroboticsclub/mini_pupper_bsp#28]
### Reproduction steps

1. Use the controller to run mini pupper,  but it walks slowly
2. Now repo does not use PCA9685 to control servo, please refer to function "send_servo_commands" in the below file,
https://github.com/mangdangroboticsclub/StanfordQuadruped/blob/mini_pupper/pupper/HardwareInterface.py

...
# this line is not for the PCA9685 chipset
pi.set_PWM_dutycycle(pwm_params.pins[axis_index, leg_index], duty_cycle)
...

### Actual results

Mini Pupper walks slowly

### Expected results

Mini Pupper can walk smoothly as the QuadrupedRobot repo

### Version

Mini Pupper

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hdumcke** [comment]
PR https://github.com/mangdangroboticsclub/mini_pupper_bsp/pull/31 should address the issue

after merge of https://github.com/mangdangroboticsclub/mini_pupper_bsp/pull/31 and https://github.com/mangdangroboticsclub/mini_pupper_bsp/pull/30 reinstall using prepare_sd script and verify if the performance meets your expectations

**Comment by mangdangroboticsclub** [comment]
already fixed, thanks!
